### PR TITLE
Add option to drawer to forceOpen on load

### PR DESCRIPTION
**Pull request by adborden**
In `fec-eregs`, we don't have any landing content for the regulations, so when you go to https://fec-prod-eregs.18f.gov/regulations/4 on smaller screens, it's unclear to the user where to go next. By adding an option to force the drawer open, even on smaller screens, we give the user a clue as to what actions are available.

`fec-eregs` can enable this options by setting `window.regs.drawer.forceOpen = true` before initializing the drawer.

I'm open to other ideas, I couldn't find an obvious way to detect that there's no landing content and condition it based on that.

### CODE REVIEW

**Comment by cmc333333** [comment]
I don't think this hurts anything, but it might be the wrong solution to this problem. Don't you _want_ there to be landing page content?

**Comment by adborden** [comment]
I think you're right, but we won't have content anytime in the near future. Some background here https://github.com/18F/fec-eregs/issues/134#issuecomment-228232094

cc @porta-antiporta

**Comment by cmc333333** [comment]
Merging now for quick turn around, but I worry it's a short-sighted solution. There's no way for developers to know this configuration exists, and once they find it, they need to override a template to use it.

Here's one alternative: We already pass in _one_ global JS setting: `APP_PREFIX` within `base.html`. We could easily extend that to include some app-wide JS settings. Then users wouldn't need to mess around with templates at all and we could document the features within the settings file.

**Comment by porta-antiporta** [comment]
appreciate the merge for the current solution. what's the best way to not lose sight of @cmc333333's proposal ^^?  Open an issue in `eregs` (to extend `app_prefix`) and `fec-eregs` (to consumer the new setting)?

**Pull request merged**
