### PR TITLE
cleaning up extract background highlight

### PR DESCRIPTION
**Pull request by donjo**
Cleaning this up so it doesn't go the full width of the screen due to node

Not sure if this is the best way to style this.

screen shot 2016-04-28 at 2 42 59 pm

### CODE REVIEW

**Comment by cmc333333** [comment]
This doesn't work for `EXTRACT`s with multiple paragraphs:

Old
screen shot 2016-04-29 at 2 50 04 pm

New
screen shot 2016-04-29 at 2 50 56 pm

What would ideal markup look like? Maybe we can generate better markup rather than trying to fix via style sheets.

**Comment by donjo** [comment]
Almost forgot about this one...

So the problem here is that the extract wrapper wraps all of `node.html` which in addition to having the paragraphs of content we want, also includes the "comment on this section" links off to the right side. If you style the whole content area (like how it is now) you get a lot of extra grey off to the right where there is a 200px padding. 

So one option would be rewriting that in a way that the content area itself is 70-80% wide and then comment links are statically positioned to the right relative to the paragraph they're referencing. 

Another option would be finding a way to wrap the paragraphs within the node in a specific class when they are an extract without implying that they'll always be two levels below the extract div.

This may not be so important right now because in my initial scanning I don't think the eManifest rule even uses this unless I missed something.

**Comment by cmc333333** [comment]
It's tricky to know what it'll use without having the final XML. I added a few extracts near the equations as _other_ proposals used extracts, but yet others used images for everything.

@xtine What do you think the best approach is here? I'm inclined to agree that the current solution of having the links be part of the "node" div doesn't work well with nesting. Using the statically positioned links may be a better approach.

I don't think that wrapping the paragraphs will work. The nodes within an "Extract" node don't necessarily know that they're within one. Even if they did, we'd need to "unindent" each paragraph to line up the extract nodes correctly. It seems much more messy than trying to create a real container to begin with.

**Comment by xtine** [comment]
For this to work without the need of modifying templates and changing nesting, we can resize `#preamble-read` to width 80% and remove padding on `.node` classes. This will also resize footnotes and footer nav divs accordingly. Even if we don't want that to happen, then we can just resize the `<ul>` containing section items instead of the entire preamble div.

**Comment by xtine** [comment]
An update: so `#preamble-read` actually needs to stay at full width because the right side space is needed for paragraph hover to write a comment targets.

**Comment by cmc333333** [comment]
@xtine If I understand correctly, you're saying we need the full width so that a user can hover on the paragraph, see the link, move the mouse to the right (no longer hovering on the paragraph text) and click the link. Switching to a 80% width paragraph would break the hover once the mouse moved to the right. Is that correct?

If so, could we do something tricksy like put the link in a second block, which, when hovered made the link visible? The link would be visible so long as the user hovered over the paragraph text _or_ the right side.

**Comment by xtine** [comment]
@cmc333333: I actually thought of a similar solution, PR at eregs/notice-and-comment#364

**Pull request closed without merging**
