### PR TITLE
Better attachments

### PR DESCRIPTION
**Pull request by donjo**
A few things to note/look for...
- I used a human readable filesize lib @jmcarp picked out but I don't necessarily know if I implemented it the preferred way.
- I had to refactor some CSS that styled all button elements under `#comment-review` because they were preventing the file upload from being styled.
- Are there any problems with that `<input>` styling hack in general?
- My text editor removed some whitespace on random stuff.
- Did I break tests by restructuring some of that attachment HTML? If so, I should probably learn how that all works and fix accordingly.
- There's going to be a PR in notice-and-comment that goes with this that you'll have to checkout at the same time to test or the buttons will be messed up. eregs/notice-and-comment#182

## Images 
screen shot 2016-04-21 at 8 18 39 pm

screen shot 2016-04-21 at 8 18 50 pm

screen shot 2016-04-21 at 8 19 39 pm

### CODE REVIEW

**Comment by xtine** [comment]
> Running "browserify:dist" (browserify) task
> Fatal error: Cannot find module 'filesize'

Did you include the module?

**Comment by cmc333333** [comment]
Holding off on this pre demo

**Comment by jmcarp** [comment]
This looks fine to me; @xtine, any chance you ran `compile_frontend` with the `--no-install` flag?

@donjo: do you prefer to show progress by a text with the percent complete vs a horizontal bar whose width reflects the progress? I had the vague thought of switching to the width-based progress bar, and only added the text-based progress because it was quick.

**Comment by xtine** [comment]
> --no-install flag
D'oh! My oversight. 😑

**Comment by donjo** [comment]
@jmcarp actually yeah a progress bar was going to be my end goal but as someone who's learning how to code on the fly as I do this I didn't know how deep of a rabbit hole I'd be going down. One idea I had that I was going to pursue was making the background color of the `.comment-attachment` fill in from left to right as it goes from 0 to 100. If that's not too difficult I'd love to play around with that.

**Comment by cmc333333** [comment]
Merging this as we've got a few :+1:s. We can swing back to making a progress bar.

**Pull request merged**
