### PR TITLE
Reviewing comment style tweaks

### PR DESCRIPTION
**Pull request by xtine**
eregs/notice-and-comment#167

screen shot 2016-04-21 at 1 12 01 pm

### CODE REVIEW

**Comment by cmc333333** [comment]
This isn't quite right. Consider 
```478.32(A)(5)(Ii)```
This should be
```478.32(a)(5)(ii)```
I don't think this is a good way to fix the underlying problem -- we're including styles that don't match the resulting pdf.

**Comment by xtine** [comment]
Ah, how about neutralizing `text-transform` altogether?

screen shot 2016-04-21 at 5 32 07 pm

Then the issue of the PDF remains. How is that styled?

**Comment by cmc333333** [comment]
Right now we're using http://wkhtmltopdf.org/, which I'm betting has some default stylesheets for headers, `strong`, etc like any other browser.

I was originally thinking we could do an iframe, which would guarantee no styles from our site leaked in. Unfortunately, we wouldn't be able to interact with it via the `Edit this comment` links. Is there a good way to nullify _all_ styles for a particular chunk of the DOM?

**Comment by xtine** [comment]
There's actually a cool way to do just that: https://developer.mozilla.org/en-US/docs/Web/CSS/all
But unfortunately, there isn't support for most browsers including Safari and IE. There are a few other similar hacks, but if we just know which properties to unset we could just default them using a * selector...

**Pull request merged**
