### PR TITLE
Update comment form interactions.

### PR DESCRIPTION
**Pull request by jmcarp**
* Highlight form tab on select
* Show text input on dependent input when no values

[Resolves https://github.com/eregs/notice-and-comment/issues/272]

### CODE REVIEW

**Comment by donjo** [comment]
Functionally looks good to me. 👍

**Comment by cmc333333** [comment]
Please don't merge until https://github.com/eregs/notice-and-comment/pull/278#issuecomment-218905280 is resolved

**Comment by cmc333333** [comment]
My head's on straight now. Good to go!

**Comment by cmc333333** [comment]
Mind adding some unit tests around this?

**Pull request merged**
