### PR TITLE
adding icons to paragraph level commenting

### PR DESCRIPTION
**Pull request by donjo**
fixes eregs/notice-and-comment#60

adds the icons and styles referenced in the issue above. 

screen shot 2016-04-12 at 5 04 54 pm

### CODE REVIEW

**Comment by cmc333333** [comment]
This would be a really good use case for an image or an icon font rather than embedding the SVG -- that template is repeated dozens (in some cases, hundreds) of times; repeating the embedded SVG significantly increases the page size. In this case, `/preamble/2016_02749/VI` jumps from 153K to 345K.

Are we planning to manipulate these SVG via JS? If not, let's just use an image or an icon font.

**Comment by donjo** [comment]
@xtine what do you think? Should we go images across the board? Is there a better way to do the template so it's not repeated a ton of times in the compiled version?

**Comment by xtine** [comment]
@donjo yeah I had a thought that maybe we should just implement the font icons since they are used a lot now. I was originally using SVGs thinking it was only a few icons but now they are repeated a lot.

**Comment by cmc333333** [comment]
IIRC, svg images can reference external style sheets, which _may_ get you where you want to be without using a font.

**Comment by donjo** [comment]
[This](https://css-tricks.com/svg-use-with-external-reference-take-2/) is possibly an option but it sounds like that may not work on some older browsers. I think the font icons have accessibility concerns right? I guess we can go with the images version.

**Comment by cmc333333** [comment]
@donjo not all browsers will load web fonts, but that's not a big deal if we have a text backup, which I think we do here? The icon is dressing :)

**Comment by cmc333333** [comment]
You're a quick study, @donjo , very nice

**Pull request merged**
